name: naani
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_mlkit_object_detection: ^0.12.1
  google_mlkit_commons: ^0.7.1
  path_provider: ^2.1.3
  image: ^4.1.7
  image_picker: ^1.1.0
  get: ^4.6.6
  camera: ^0.10.5+9
  path: ^1.9.0
  http: ^1.2.1
  pin_code_fields: ^8.0.1
  dio: ^5.4.3+1
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/info_screen/
    - assets/img/signupscreen/
    - assets/img/exercise/
    - assets/ML/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: fonts/Poppins-Bold.ttf
          weight: 800
