List<String> eyeCareTips = [
  "Take regular breaks using the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds.",
  "Wear sunglasses that block 100% of UVA and UVB rays.",
  "Keep your computer screen at an arm's length away and slightly below eye level.",
  "Ensure proper lighting while reading or using a computer.",
  "Maintain a healthy diet rich in omega-3 fatty acids, vitamins C and E, and zinc.",
  "Stay hydrated by drinking plenty of water throughout the day.",
  "Avoid smoking to reduce the risk of eye diseases like cataracts and macular degeneration.",
  "Get regular eye exams to detect and treat problems early.",
  "Blink often to keep your eyes moist, especially when using digital screens.",
  "Use artificial tears to prevent dry eyes.",
  "Adjust the brightness and contrast of your screen to comfortable levels.",
  "Position your screen to reduce glare from windows or lights.",
  "Take breaks from contact lenses to let your eyes breathe.",
  "Clean your hands before touching your eyes or handling contact lenses.",
  "Replace your contact lens case every three months to avoid infections.",
  "Follow your eye care provider's instructions for contact lens care.",
  "Get enough sleep to keep your eyes refreshed.",
  "Wear protective eyewear when engaging in activities that could harm your eyes.",
  "Eat plenty of leafy greens like spinach and kale for eye health.",
  "Limit screen time to avoid digital eye strain.",
  "Use an anti-glare screen protector for your computer or smartphone.",
  "Avoid rubbing your eyes to prevent irritation or infection.",
  "Use a humidifier to add moisture to the air and prevent dry eyes.",
  "Wear a hat with a brim to protect your eyes from the sun.",
  "Manage chronic conditions like diabetes and hypertension that can affect your eyes.",
  "Keep your prescription glasses up to date.",
  "Avoid staring at digital screens for extended periods without a break.",
  "Do eye exercises to strengthen your eye muscles.",
  "Consult an eye doctor if you experience any changes in vision.",
  "Reduce blue light exposure by using blue light filters on digital devices."
];

List<String> eyeCareFacts = [
  "The human eye can distinguish approximately 10 million different colors.",
  "Eyes are made up of over 2 million working parts.",
  "Your eyes focus on 50 different objects every second.",
  "80% of all learning comes through the eyes.",
  "Newborns don't produce tears until they are 4-13 weeks old.",
  "An average person blinks 15-20 times per minute.",
  "The human eye weighs approximately 8 grams and is about 24 millimeters wide.",
  "Heterochromia is a condition where a person has two different colored eyes.",
  "Your eyes can get sunburned, a condition called photokeratitis.",
  "Diabetes is the leading cause of blindness in adults.",
  "The only organ more complex than the eye is the brain.",
  "The muscles that move your eyes are the fastest and strongest muscles in your body.",
  "Eye transplants are currently impossible due to the complexity of the optic nerve.",
  "People with blue eyes share a common ancestor with every other blue-eyed individual.",
  "The first eye exam dates back to ancient Egypt around 1,500 BC."
];
